### ISSUE TITLE
Plugin blocks indentation using TAB

### ISSUE THREAD

**Issue by kryonix** [gatapia/unicode-math-vscode#1]
I can not longer use tab for indentation with this extension activated.
Instead the following message pops up:
```
Running the contributed command:'unicode-math-vscode.commit' failed.
```

Is it possible to have both, symbol completion, and indentation using tab?

**Comment by gatapia** [comment]
This was a bug introduced in a recent commit.  This is fixed.  Please let me know if you still have issues after an upgrade.

**Comment by kryonix** [comment]
Great, this works now. But there is still a slight issue.
The options `editor.tabSize` and `editor.insertSpaces` are not considered.
This means that there is always a `tab` (\t) inserted, instead of e.g. two spaces.

**Comment by kryonix** [comment]
I've never implemented a vscode extension, but I think this might be a solution for this issue?

```patch
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -53,7 +53,8 @@ class UnicodeMaths {
        }

        private sendTab() {
+               commands.executeCommand('tab');
-               commands.executeCommand('type', { source: 'keyboard', text: '\t' });
        }
```
