### ISSUE TITLE
Can't input uppercase letters as subscript

### ISSUE THREAD

**Issue by honi** [gatapia/unicode-math-vscode#14]
Is this behavior intended?
```
X\_l
Renders:
Xₗ
```

But if I try with an uppercase L it doesn't work:
```
X\_L
Renders:
X\_L
```

**Comment by gatapia** [comment]
Unfortunately not all subscript/superscript characters are represented in unicode.  List is here: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts.  I actually dont think any uppercase character has a subscript couterpart.

**Comment by honi** [comment]
Oh, I see. Ok then, thanks for the response!
