### ISSUE TITLE
allow custom symbols

### ISSUE THREAD

**Issue by medovina** [gatapia/unicode-math-vscode#8]
This is a great plugin.  However, it would be even better if I could specify a custom set of symbols that extend or override the built-in symbol set.  Perhaps you could make this configurable either through the Visual Studio Code settings, or through an external configuration file - either way would be fine with me.

**Comment by gatapia** [comment]
This is actually the complete set of available unicode symbols (unless its been updated recently). So there is really nothing to 'configure'.  pls correct me if im wrong

**Comment by medovina** [comment]
Well, actually I found that this plugin does have the one symbol I thought was missing (¬) - I realized it was called "neg".  So at the moment I am satisfied - the plugin supports all the symbols I need.  Given that, I'll close this.
